# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
    
    - name: Verify Java version
      run: java -version

    - name: Set up Ant
      run: sudo apt-get install -y ant

    - name: Verify build.xml exists
      run: ls -l WebDevNSBM/build.xml

    - name: Build with Ant
      run: ant -noinput -buildfile WebDevNSBM/build.xml

